### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by bernhardh** [chinleung/laravel-nova-optimizer#2]
Can you please explain, what this packages does?

**Comment by chinleung** [comment]
> Can you please explain, what this packages does?

Hey @bernhardh,

I use this package to reduce the number of n+1 queries when using queries in Nova actions. Sometimes, I have to fill the options of Select fields with models from the database, which can create lots of queries since Nova will run the same query for each model even though it's the same action class.

For instance, you have a Select field which returns the list of users, in a resource with 10 records. It will perform the user query 10 times.

Only using this for personal projects at the moment.
